packages:
  updater:
    interfaces:
      DockerHubClient:
        config:
          dir: .
          filename: dockerhub_client_mock.go
          structname: DockerHubClientMock
          pkgname: main
