packages:
  updater:
    interfaces:
      DockerHubClient:
        config:
          dir: .
          filename: command_dockerhub_client_mock.go
          structname: DockerHubClientMock
          pkgname: main
      FileSystemOperator:
        config:
          dir: .
          filename: updater_file_system_operator_mock.go
          structname: FileSystemOperatorMock
          pkgname: main
      EndpointChecker:
        config:
          dir: .
          filename: updater_endpoint_checker_mock.go
          structname: EndpointCheckerMock
          pkgname: main
      SingleAppUpdater:
        config:
          dir: .
          filename: updater_single_app_updater_mock.go
          structname: SingleAppUpdaterMock
          pkgname: main
      SingleAppUpdateFileSystemOperator:
        config:
          dir: .
          filename: updater_single_app_fs_operator_mock.go
          structname: SingleAppUpdateFileSystemOperatorMock
          pkgname: main
      HealthChecker:
        config:
          dir: .
          filename: health_checker_mock.go
          structname: HealthCheckerMock
          pkgname: main